### ISSUE TITLE
No min version, file naming.

### ISSUE THREAD

**Issue by morrissey-ingenious** [ChiaraLyn/css-negative-margins-bootstrap5#1]
I would love to see a minified version of this and even the source scss provided in the repository along with changing the file name from `style.css` to something like `bootstrap-negative-margins.css`

**Comment by ChiaraLyn** [comment]
Hi @morrissey-ingenious, 
thank you very much for your valuable contribution!
I renamed the file and added a minified version to the repository.
I didn't insert the sass source because as per Bootstrap 5 documentation: "negative margins are disabled by default, but can be enabled in Sass by setting $enable-negative-margins: true.", so I created css classes manually, using the bootstrap.min.css file (using the unminified version).

See you soon and thanks again!
